version: "3"

services:
  database:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "ssa"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  api:
    #build:
    #  context: .
    #  dockerfile: ./Dockerfile
    image: ghcr.io/mawoka-myblock/simpleselfhostauth:master
    restart: always
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgresql://postgres:password@database:5432/ssa
      REDIS_URL: redis://redis:6379/0
      SECRET_KEY: NOT_SECRET # RUN openssl rand -hex 32
    depends_on:
      - database
      - redis
  redis:
    image: redis:alpine
    restart: always

volumes:
  postgres-data: